version: 2
jobs:
  build:
    working_directory: ~/workspace

    docker:
      # Docker image provided by CircleCI with pre-installed java, node and chrome
      # https://hub.docker.com/r/circleci/openjdk/
      - image: circleci/openjdk:8-jdk-node-browsers

    steps:
      # Check out the master branch of the project repository
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # Run the backend java tests
      - run:
          name: Run server tests
          command: gradle test

      # Run the frontend js tests
      - run:
          name: Run client tests
          command: gradle testFrontend

      # Save test result reports
      - run:
          name: Save test results
          command: |
              mkdir -p ~/junit/
              find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

      # TODO: on a successful build => deploy to heroku