version: 2
jobs:
  build:
    working_directory: ~/workspace

    docker:
      # Docker image provided by CircleCI with pre-installed java, node and chrome
      # https://hub.docker.com/r/circleci/openjdk/
      - image: circleci/openjdk:8-jdk-node-browsers

    steps:
      # Check out the master branch of the project repository
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # Run the backend java tests
      - run:
          name: Run Server Tests
          command: gradle test

      # Run the frontend js tests
      - run:
          name: Run Client Tests
          command: gradle testFrontend

      # Save test result reports
      # see https://circleci.com/docs/2.0/collect-test-data/
      - run:
          name: Save Test Results
          command: |
              mkdir -p ~/junit/
              find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

  deploy:
    machine: true

    steps:
      - checkout

      - run:
          name: Build Docker Image
          command: docker build -t movies

      - run:
          name: Deploy to Heroku
          command: |
              docker login --username=$HEROKU_USER_NAME --password=$HEROKU_API_KEY registry.heroku.com
              docker tag movies registry.heroku.com/$HEROKU_APP_NAME/web
              docker push registry.heroku.com/$HEROKU_APP_NAME/web

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master